In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import recall_score, accuracy_score, classification_report, f1_score
from xgboost import XGBClassifier
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(r"D:\Data Analytics & Data Science\NetMax Technologies\DataSet From claude\diabetic_readmission_dataset.csv")
df.head(20)

    patient_id       age  gender  ... change diabetesMed  readmitted
0       100000   [50-60)  Female  ...     Ch          No           0
1       100001   [80-90)  Female  ...     Ch         Yes           1
2       100002   [70-80)    Male  ...     Ch          No           0
3       100003   [60-70)  Female  ...     Ch         Yes           0
4       100004   [40-50)  Female  ...     No          No           0
5       100005   [40-50)    Male  ...     Ch         Yes           0
6       100006   [20-30)  Female  ...     Ch         Yes           0
7       100007   [80-90)    Male  ...     No          No           0
8       100008   [60-70)  Female  ...     No         Yes           0
9       100009   [70-80)    Male  ...     No          No           1
10      100010   [10-20)  Female  ...     No          No           0
11      100011  [90-100)    Male  ...     No          No           0
12      100012   [70-80)  Female  ...     No         Yes           1
13      100013   [40-50)    Male  ...     Ch          No           0
14      100014   [40-50)  Female  ...     Ch         Yes           0
15      100015   [40-50)  Female  ...     No         Yes           1
16      100016   [50-60)  Female  ...     Ch         Yes           0
17      100017   [60-70)  Female  ...     Ch         Yes           0
18      100018   [60-70)    Male  ...     No         Yes           0
19      100019   [50-60)  Female  ...     No         Yes           0

[20 rows x 20 columns]

In [6]:
df.isnull().sum()

patient_id            0
age                   0
gender                0
race                  0
admission_type        0
time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
number_diagnoses      0
primary_diagnosis     0
max_glu_serum         0
A1Cresult             0
insulin               0
change                0
diabetesMed           0
readmitted            0
dtype: int64

In [5]:
# handling missing values

df["num_lab_procedures"] = df["num_lab_procedures"].fillna(df["num_lab_procedures"].median())

df["max_glu_serum"] =df["max_glu_serum"].fillna(df["max_glu_serum"].mode()[0])

df["A1Cresult"] = df["A1Cresult"].fillna(df["A1Cresult"].mode()[0])

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.head()

   patient_id      age  gender  ... change diabetesMed  readmitted
0      100000  [50-60)  Female  ...     Ch          No           0
1      100001  [80-90)  Female  ...     Ch         Yes           1
2      100002  [70-80)    Male  ...     Ch          No           0
3      100003  [60-70)  Female  ...     Ch         Yes           0
4      100004  [40-50)  Female  ...     No          No           0

[5 rows x 20 columns]

In [10]:
df["A1Cresult"].value_counts()

A1Cresult
>8      5935
>7      1245
Norm     820
Name: count, dtype: int64

In [14]:
# hanlding categorical data

label = LabelEncoder()

column = ["age","gender","race","admission_type", "primary_diagnosis","max_glu_serum","A1Cresult","insulin","change","diabetesMed"]
for item in column:
    df[item] = label.fit_transform(df[item])

In [15]:
df.head()

   patient_id  age  gender  race  ...  insulin  change  diabetesMed  readmitted
0      100000    5       0     2  ...        1       0            0           0
1      100001    8       0     2  ...        1       0            1           1
2      100002    7       1     2  ...        2       0            0           0
3      100003    6       0     2  ...        1       0            1           0
4      100004    4       0     4  ...        2       1            0           0

[5 rows x 20 columns]

In [16]:
df.drop("patient_id", axis=1, inplace=True)

In [17]:
df.head()

   age  gender  race  admission_type  ...  insulin  change  diabetesMed  readmitted
0    5       0     2               2  ...        1       0            0           0
1    8       0     2               1  ...        1       0            1           1
2    7       1     2               1  ...        2       0            0           0
3    6       0     2               0  ...        1       0            1           0
4    4       0     4               0  ...        2       1            0           0

[5 rows x 19 columns]

In [18]:
# feature selection
x = df.drop(columns=["readmitted"])
y = df["readmitted"]

In [19]:
from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [22]:
# using logistics regression

model_logistic_regressor = LogisticRegression(max_iter=100)

model_logistic_regressor.fit(x_train,y_train)

d:\Data Analytics & Data Science\General Practice\General ML practise\rana\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [28]:
y_pred_lr = model_logistic_regressor.predict(x_test)
acc_lr= accuracy_score(y_test,y_pred_lr)
print(f"Accuracy score with Logistic Regression: {acc_lr:.2f}")

Accuracy score with Logistic Regression: 0.86

In [25]:
from sklearn.metrics import confusion_matrix


confusion_matrix(y_test,y_pred_lr)

array([[1355,   12],
       [ 214,   19]])

In [27]:
# scaling the data to improve the accuracy 

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [30]:
model_logistic_regressor.fit(x_train_scaled,y_train)

LogisticRegression()

In [33]:
y_pred_scaled_lr = model_logistic_regressor.predict(x_test_scaled)
acc_scaled_lr = accuracy_score(y_test,y_pred_scaled_lr)
print(f"Accuracy score with scaled data (Logistic Regression) : {acc_scaled_lr:.2f}")

Accuracy score with scaled data (Logistic Regression) : 0.86

In [34]:
confusion_matrix(y_test,y_pred_scaled_lr)

array([[1351,   16],
       [ 210,   23]])

In [35]:
# using xgboost ang grid search

import random

from sklearn.model_selection import GridSearchCV


best_para = {"max_depth" :[3,5,7,12],
             "n_estimators" : [200,250,300,350]}

model = RandomForestClassifier(random_state=42)

grid_search=GridSearchCV(estimator=model,
                         param_grid=best_para,
                         cv=5,
                         n_jobs=-1,
                         verbose=1)

grid_search.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, 12],
                         'n_estimators': [200, 250, 300, 350]},
             verbose=1)

In [36]:
best_model = grid_search.best_estimator_

In [37]:
y_pred_xg = best_model.predict(x_test_scaled)
acc_xg = accuracy_score(y_test,y_pred_xg)
print(f"Accuracy score with XGBOOST: {acc_xg:.2f}")

Accuracy score with XGBOOST: 0.86

In [38]:
confusion_matrix(y_test,y_pred_xg)

array([[1366,    1],
       [ 229,    4]])

In [40]:
classification_report(y_test,y_pred_xg)

'              precision    recall  f1-score   support\n\n           0       0.86      1.00      0.92      1367\n           1       0.80      0.02      0.03       233\n\n    accuracy                           0.86      1600\n   macro avg       0.83      0.51      0.48      1600\nweighted avg       0.85      0.86      0.79      1600\n'